service: dio-course-certificate
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.certificatesTableName}

custom:
  certificatesTableName: course-certificate-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  createCertificate:
    handler: src/api.createCertificate
    name: create-certificate
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: certificate
          method: post
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt CertificatesTable.Arn
  getCertificate:
    handler: src/api.getCertificate
    name: get-certificate
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: certificate/{id}
          method: get
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt CertificatesTable.Arn
  updateCertificate:
    handler: src/api.updateCertificate
    name: update-certificate
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: certificate/{id}
          method: put
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt CertificatesTable.Arn
  deleteCertificate:
    handler: src/api.deleteCertificate
    name: delete-certificate
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: certificate/{id}
          method: delete
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt CertificatesTable.Arn

resources:
  Resources:
    CertificatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.certificatesTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH